name: build

on:
  push:
    branches:
      - dev
      - release
      - main

env:
  DOCKERHUB_REPO_NAME: basic-action

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare Docker Image Tag
        id: prep
        run: |
          if [[ $GITHUB_REF == refs/heads/dev ]]; then
            TAG=$(git rev-parse --short=8 ${{ github.sha }})
          elif [[ $GITHUB_REF == refs/heads/release ]]; then
            TAG=${{ github.event.head_commit.message }}
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            TAG=${{ 'latest' }}
          fi
          echo ::set-output name=image_tag::${TAG}
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        run: docker build -t $DOCKERHUB_REPO_NAME .
      - name: Tags
        run: docker tag $DOCKERHUB_REPO_NAME ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKERHUB_REPO_NAME:${{ steps.prep.outputs.image_tag }}
      - name: Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKERHUB_REPO_NAME:${{ steps.prep.outputs.image_tag }}
