name: hello-world
on:
  push:
    branches:
      - main
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello-main
        env:
          webname: ${{ secrets.SECRET_WEBNAME }}
        run: echo "Hello $webname"
