name: hello-feature
on:
  push:
    branches:
      - 'feature/*'

jobs:
  feature-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello-feature
        run: echo "Hello Feature"
      - name: hello-branch
        run: echo "Hello ${{ github.ref }}"
      - name: hello-sha
        run: echo "Hello ${{ github.sha }}"
      - name: Prepare Docker Image Tag
        id: prep
        run: echo ::set-output name=image_tag::${{ github.event.head_commit.message }}