name: hello-feature
on:
  push:
    branches:
      - 'feature/*'
jobs:
  feature-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello-feature
        run: echo "Hello Feature"
      - name: hello-branch
        run: echo "Hello ${{ github.ref }}"
      - name: hello-sha
        run: echo "Hello ${{ github.sha }}"
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        run: docker build -t basic-action .
      - name: Tags
        run: |
          docker tag basic-action ${{ secrets.DOCKERHUB_USERNAME }}/basic-action:${{ github.sha }}
          docker tag basic-action ${{ secrets.DOCKERHUB_USERNAME }}/basic-action:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/basic-action:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/basic-action:latest
