name: hello-feature
on:
  push:
    branches:
      - 'feature/*'
jobs:
  feature-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello-feature
        run: echo "Hello Feature"
      - name: hello-branch
        run: echo "Hello ${{ github.ref }}"
      - name: hello-sha
        run: echo "Hello ${{ github.sha }}"
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: basic-action:${{ github.sha }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
